In [1]:

import pandas as pd
import numpy as np
import json
from pandas.io.json import json_normalize

In [9]:
file_ = input('Introduce el nombre del archivo: ')
with open('files/{file}.json'.format(file=file_), encoding='utf-8') as file:
    df = pd.read_json(file).astype(str)


df.drop_duplicates(keep='first',ignore_index=True,inplace=True)

df = df[~((df.rating == "['ND']") & (df.year == "['ND']") &
    (df.budget == "['ND']") & (df.boxOffice_collection == "['ND']") &
    (df.cast == "nan") & (df.personajes == "nan"))
    ]

df.to_csv('files/{file}.csv'.format(file = file_),index=False)
df
#df.dropna(subset=['genre','rati=ng','year','duracion','busget','boxOffice_collection'],inplace=False)

,id_imdb,title,genre,rating,year,pais_de_origen,idiomas,duracion,estreno,budget,boxOffice_collection,cast,personajes,director,guionista,plot
0,['tt12593682'],['Bullet Train'],"['Action', 'Comedy', 'Thriller']",['7.4'],['2022'],"['United States', 'Japan']","['English', 'Japanese', 'Spanish', 'Russian']",['2h 7m'],[0],"['$85,900,000 (estimated)']","['$173,614,688']","['Brad Pitt', 'Joey King', 'Aaron Taylor-Johns...","['Ladybug', 'Prince', 'Tangerine', 'Lemon', 'K...",[''],[''],['']
1,['tt0955308'],['Robin Hood'],"['Action', 'Adventure', 'Drama']",['6.6'],['2010'],"['United States', 'United Kingdom']","['English', 'French', 'Ukrainian']",['2h 20m'],[0],"['$200,000,000 (estimated)']","['$321,669,741']","['Russell Crowe', 'Cate Blanchett', 'Matthew M...","['Robin Longstride', 'Marion Loxley', 'Sheriff...",[''],[''],['']
2,['tt13320622'],['The Lost City'],"['Action', 'Adventure', 'Comedy']",['6.1'],['2022'],['United States'],"['English', 'Spanish', 'Latin', 'French']",['1h 52m'],[0],"['$68,000,000 (estimated)']","['$190,844,029']","['Sandra Bullock', 'Channing Tatum', 'Daniel R...","['Loretta Sage', 'Alan', 'Abigail Fairfax', 'B...",[''],[''],['']
3,['tt9419884'],['Doctor Strange in the Multiverse of Madness'],"['Action', 'Adventure', 'Fantasy']",['7.0'],['2022'],['United States'],"['English', 'Spanish', 'Chinese']",['2h 6m'],[0],"['$200,000,000 (estimated)']","['$955,152,198']","['Benedict Cumberbatch', 'Elizabeth Olsen', 'C...","['Doctor Stephen Strange', 'Wanda Maximoff', '...",[''],[''],['']
4,['tt5108870'],['Morbius'],"['Action', 'Adventure', 'Horror']",['5.2'],['2022'],['United States'],"['English', 'Spanish', 'Russian']",['1h 44m'],[0],"['$75,000,000 (estimated)']","['$167,460,961']","['Jared Leto', 'Matt Smith', 'Adria Arjona', '...","['Dr. Michael Morbius', 'Milo', 'Martine Bancr...",[''],[''],['']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6618,['tt2957774'],['The White Storm'],"['Action', 'Crime', 'Thriller']",['6.6'],['2013'],"['China', 'Hong Kong']","['Cantonese', 'English', 'Thai']",['2h 20m'],[0],"['$44,670,277']",['ND'],"['Ching Wan Lau', 'Louis Koo', 'Nick Cheung', ...","['Ma Ho-tin', 'So Kin-chow', 'Cheung Tsz-wai',...",[''],[''],['']
6619,['tt4943558'],['Saheb Bibi Golaam'],"['Action', 'Crime', 'Drama']",['6.4'],['2016'],['India'],['Bengali'],['2h 1m'],[0],['ND'],['ND'],"['Damini Basu', 'Ritwick Chakraborty', 'Vikram...","['Ratna', 'Javed', 'Zico', 'Nakul', 'Jimmy', '...",[''],[''],['']
6620,['tt0364734'],['Guns and Guts'],"['Action', 'Adventure', 'Crime']",['5.0'],['1974'],['Mexico'],['Spanish'],['1h 38m'],[0],['ND'],['ND'],"['Jorge Rivero', 'Pedro Armendáriz Jr.', 'Roge...","['El Pistolero', 'Esposo abandonado', 'Prision...",[''],[''],['']
6621,['tt0135790'],['Bang Boom Bang - Ein todsicheres Ding'],"['Action', 'Comedy', 'Crime']",['7.5'],['1999'],['Germany'],"['German', 'Danish']",['1h 50m'],[0],['ND'],['ND'],"['Oliver Korittke', 'Markus Knüfken', 'Ralf Ri...","['Keek', 'Andy', 'Kalle Grabowski', 'Werner Ka...",[''],[''],['']
6622,['tt21030012'],['Primary Position'],"['Action', 'Drama', 'War']",['ND'],['2022'],['United States'],['English'],['ND'],"['Releases November 11, 2022']","['$750,000 (estimated)']",['ND'],"['Robert Amparan', 'Omar Gooding', 'Kris D. Lo...","['Darnell Jackson', 'Corporal Doug Richards', ...",[''],[''],['']